[package]
name = "nesemu"
version = "0.1.0"
edition = "2024"

[dependencies]
bitflags = "2.5.0"
lazy_static = "1.5.0"
sdl2 = "0.34.0"
rand = "=0.8"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

eframe = "0.27.2"
native-dialog = "0.7.0"